services:
  database:
    image: postgres:18-alpine
    container_name: "socialsync_database"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_DB: ${DB_NAME:-shopizdb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pg-data-shopiz:/var/lib/posgresql/data

volumes:
  pg-data-shopiz: